export enum UserActionTypes {
    FETCH_USERS = 'FETCH_USERS',
    FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS',
    FETCH_USERS_ERROR = 'FETCH_USERS_ERROR'
}

export enum AuthActionTypes {
    AUTH_MODAL = 'AUTH_MODAL',
    AUTH_ERROR = 'AUTH_ERROR'
}